---
title: "brian_EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading-libraries}
library(tidyverse)
library(dplyr)
library(broom)
library(knitr)
library(tidyr)
```

```{r loading-data, message=F, warning=F}
matches <- read_csv("data/international_matches.csv")
```

```{r home-field-advantage}
neutral_matches <- matches %>%
  filter(neutral_location == T) %>%
  mutate(goal_differential = home_team_score - away_team_score) %>%
  mutate(fifa_rank_differential = away_team_fifa_rank - home_team_fifa_rank)

ggplot(data = neutral_matches, aes(x = fifa_rank_differential,
                                   y = goal_differential)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", formula = y ~ x, color = "red") +
  labs(x = "FIFA Rank Differential",
       y = "Goal Differential",
       title = "Goal Differential as FIFA Rank Differential Varies",
       subtitle = "Positive FIFA Differential Means Home Team is Ranked Higher\nPositive Goal Differential Means Home Team Won")
```

```{r position-scores}
position_score_matches <- matches %>%
  filter(!is.na(home_team_goalkeeper_score) &
           !is.na(away_team_goalkeeper_score))
```






```{r data-cleaning}
# MUST RUN SEANS CODE FIRST FOR THIS TO WORK
true_data <- final_dataset %>%
  select(-c(home_team_total_fifa_points,
            away_team_total_fifa_points,
            tournament,
            city,
            country,
            shoot_out,
            home_team_continent,
            away_team_continent)) %>%
  filter(year != 2002)


true_data <- true_data %>%
  filter(!is.na(home_team_goalkeeper_score) &
         !is.na(away_team_goalkeeper_score) &
         !is.na(home_team_mean_defense_score) &
         !is.na(away_team_mean_defense_score) &
         !is.na(home_team_mean_offense_score) &
         !is.na(away_team_mean_offense_score) &
         !is.na(home_team_mean_midfield_score) &
         !is.na(away_team_mean_midfield_score))

matches <- true_data %>%
  mutate(goalkeeper_differential = home_team_goalkeeper_score - away_team_goalkeeper_score) %>%
  mutate(defense_differential = home_team_mean_defense_score - away_team_mean_defense_score) %>%
  mutate(offense_differential = home_team_mean_offense_score - away_team_mean_offense_score) %>%
  mutate(midfield_differential = home_team_mean_midfield_score - away_team_mean_midfield_score) %>%
  select(-c(home_team_goalkeeper_score,
            away_team_goalkeeper_score,
            home_team_mean_defense_score,
            away_team_mean_defense_score,
            home_team_mean_offense_score,
            away_team_mean_offense_score,
            home_team_mean_midfield_score,
            away_team_mean_midfield_score)) %>%
  mutate(possesion_differential = hPossesion - aPossesion) %>%
  mutate(shots_on_target_differential = hshotsOnTarget - ashotsOnTarget) %>%
  mutate(shots_differential = hshots - ashots) %>%
  mutate(yellow_cards_differential = hyellowCards - ayellowCards) %>%
  mutate(red_card_differential = hredCards - aredCards) %>%
  mutate(fouls_differential = hfouls - afouls) %>%
  mutate(saves_differential = hsaves - asaves) %>%
  select(-c(hPossesion,
            aPossesion,
            hshotsOnTarget,
            ashotsOnTarget,
            hshots,
            ashots,
            hyellowCards,
            ayellowCards,
            hredCards,
            aredCards,
            hfouls,
            afouls,
            hsaves,
            asaves)) %>%
  mutate(score_differential = home_team_score - away_team_score) %>%
  mutate(fifa_rank_differential = home_team_fifa_rank - away_team_fifa_rank) %>%
  select(-c(home_team_fifa_rank,
            away_team_fifa_rank))

write_csv(matches, "data/cleaned_matches.csv")

```


```{r}
neutral_matches <- matches %>%
  filter(neutral_location == "True")


write_csv(neutral_matches, "data/neutral_cleaned_matches.csv")
```


```{r}
world_cup_teams <- read.csv("data/Qatar2022-teams.csv", sep=";")
```


```{r}

library(readxl)
missing <- read_xlsx("data/last5.xlsx") %>%
  rename(home_team = Team,
         away_team = Away,
         hshotsOnTarget = SOT,
         hshots = Shots,
         hPossesion = Possession,
         hfouls = Fouls,
         hyellowCards = Yellow,
         hredCards = Red,
         home_team_score = hgoals,
         away_team_score = agoals) %>%
  select(-c(away_team))

past_matches <- true_data %>%
  filter(home_team %in% world_cup_teams$Team | away_team %in% world_cup_teams$Team)

past_matches <- bind_rows(past_matches, missing)
    
    
    #rbind(c(NA,team,NA,NA,NA,goals_for,goals_allowed,
    #        NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,possession,
    #        NA,shots_on_target,NA,shots,NA,yellow_cards,NA,
    #        red_cards,NA,fouls,NA,NA,NA))


world_cup_teams <- world_cup_teams %>%
  mutate(avg_goals = NA,
         avg_goalsallowed = NA,
         avg_shotsontarget = NA,
         avg_shots = NA,
         avg_possession = NA,
         avg_fouls = NA,
         avg_yellowcards = NA,
         avg_redcards = NA)

for(j in 1:nrow(world_cup_teams)){
  avg_goals = 0
  avg_goalsallowed = 0
  avg_shotsontarget = 0
  avg_shots = 0
  avg_possession = 0
  avg_fouls = 0
  avg_yellowcards = 0
  avg_redcards = 0
  
  team <- world_cup_teams[j,"Team"]
  
  country <- past_matches %>%
    filter(home_team == team | away_team == team) %>%
    slice_tail(n=5)
  #print(country)
  
  for(i in 1:nrow(country)){
    
    if(country[i,"home_team"]==team){
      avg_goals = avg_goals + country[i,"home_team_score"]
      avg_goalsallowed = avg_goalsallowed + country[i,"away_team_score"]
      avg_shotsontarget = avg_shotsontarget + country[i, "hshotsOnTarget"]
      avg_shots = avg_shots + country[i, "hshots"]
      avg_possession = avg_possession + country[i, "hPossesion"]
      avg_fouls = avg_fouls + country[i, "hfouls"]
      avg_yellowcards = avg_yellowcards + country[i, "hyellowCards"]
      avg_redcards = avg_redcards + country[i,"hredCards"]
    }
    else {
      avg_goals = avg_goals + country[i,"away_team_score"]
      avg_goalsallowed = avg_goalsallowed + country[i,"home_team_score"]
      avg_shotsontarget = avg_shotsontarget + country[i, "ashotsOnTarget"]
      avg_shots = avg_shots + country[i, "ashots"]
      avg_possession = avg_possession + country[i, "aPossesion"]
      avg_fouls = avg_fouls + country[i, "afouls"]
      avg_yellowcards = avg_yellowcards + country[i, "ayellowCards"]
      avg_redcards = avg_redcards + country[i,"aredCards"]
    }
  }
  
  avg_goals = avg_goals / 5
  avg_goalsallowed = avg_goalsallowed / 5
  avg_shotsontarget = avg_shotsontarget / 5
  avg_shots = avg_shots / 5
  avg_possession = avg_possession / 5
  avg_fouls = avg_fouls / 5
  avg_yellowcards = avg_yellowcards / 5
  avg_redcards = avg_redcards / 5
  
  world_cup_teams[j,"avg_goals"] = avg_goals
  world_cup_teams[j,"avg_goalsallowed"] = avg_goalsallowed
  world_cup_teams[j,"avg_shotsontarget"] = avg_shotsontarget
  world_cup_teams[j,"avg_shots"] = avg_shots
  world_cup_teams[j,"avg_possession"] = avg_possession
  world_cup_teams[j,"avg_fouls"] = avg_fouls
  world_cup_teams[j,"avg_yellowcards"] = avg_yellowcards
  world_cup_teams[j,"avg_redcards"] = avg_redcards
  
}

write_csv(world_cup_teams, "data/FIFA2022_GroupStageTeams.csv")

```


```{r}
ggplot(data = matches,
       aes(x = home_team_result,
           y = shots_on_target_differential)) +
  geom_boxplot()

ggplot(data = matches,
       aes(x = home_team_result,
           y = yellow_cards_differential)) +
  geom_boxplot()
```

```{r}

# group_stage <- read_xlsx("data/group_pred_with_odds.xlsx")
group_stage <- read_csv("data/results2.csv")

profit = 0
for(i in 1:nrow(group_stage))
{
  if(group_stage[i,"outcome"]=="Win" &
     group_stage[i,"pred_outcome"]=="Likely Win")
  {
    if(group_stage[i,"winOdds"]<0){
      profit = profit + (100/-group_stage[i,"winOdds"])*100
    }
    else
    {
      profit = profit + group_stage[i,"winOdds"]
    }
  }
  else if(group_stage[i,"outcome"]=="Draw" &
     group_stage[i,"pred_outcome"]=="Likely Draw")
  {
    if(group_stage[i,"drawOdds"]<0){
      profit = profit + (100/-group_stage[i,"drawOdds"])*100
    }
    else
    {
      profit = profit + group_stage[i,"drawOdds"]
    }
  }
  else if(group_stage[i,"outcome"]=="Loss" &
     group_stage[i,"pred_outcome"]=="Likely Loss")
  {
    if(group_stage[i,"loseOdds"]<0){
      profit = profit + (100/-group_stage[i,"loseOdds"])*100
    }
    else
    {
      profit = profit + group_stage[i,"loseOdds"]
    }
  }
  else
  {
    profit = profit - 100
  }

}


# print(profit %>%
#         rename(profit = winOdds))

print(profit %>%
        rename(profit = loseOdds))
```







```{r}
# print(profit2 %>%
#         rename(profit = Odds))

print(profit2 %>%
        rename(profit = drawOdds))

profit2 = 0
for(i in 1:nrow(group_stage))
{
  if(group_stage[i,"winProb"] > group_stage[i,"drawProb"] &
     group_stage[i,"winProb"] > group_stage[i,"loseProb"])
  {
    if(group_stage[i,"outcome"]=="Win" & 
       group_stage[i,"winOdds"] < 0)
    {
      profit2 = profit2 + (100/-group_stage[i,"winOdds"])*100
    }
    else if(group_stage[i,"outcome"]=="Win")
    {
      profit2 = profit2 + group_stage[i,"winOdds"]
    }
    else{
      profit2 = profit2 - 100
    }
  }
  
  else if(group_stage[i,"drawProb"] > group_stage[i,"winProb"] &
     group_stage[i,"drawProb"] > group_stage[i,"loseProb"])
  {
    if(group_stage[i,"outcome"]=="Draw" & 
       group_stage[i,"drawOdds"] < 0)
    {
      profit2 = profit2 + (100/-group_stage[i,"drawOdds"])*100
    }
    else if(group_stage[i,"outcome"] == "Draw")
    {
      profit2 = profit2 + group_stage[i,"drawOdds"]
    }
    else{
      profit2 = profit2 - 100
    }
  }
  
  else if(group_stage[i,"loseProb"] > group_stage[i,"winProb"] &
     group_stage[i,"loseProb"] > group_stage[i,"drawProb"])
  {
    if(group_stage[i,"outcome"]=="Lose" & 
       group_stage[i,"loseOdds"] < 0)
    {
      profit2 = profit2 + (100/-group_stage[i,"loseOdds"])*100
    }
    else if(group_stage[i,"outcome"] == "Lose")
    {
      profit2 = profit2 + group_stage[i,"loseOdds"]
    }
    else{
      profit2 = profit2 - 100
    }
  }
}

profit2

```



```{r}
correct_guesses <- group_stage %>%
  filter(pred_outcome == "Likely Win" & outcome == "Win" |
           pred_outcome == "Likely Draw" & outcome=="Draw" |
           pred_outcome == "Likely Loss" & outcome=="Loss")
nrow(correct_guesses)
nrow(group_stage)
```





```{r}
results_and_odds2

```








